README.md
src/views/components/column/Column.js
src/views/components/column/Resume.js
src/views/components/column/Testimonials.js
src/views/components/column/Title.js

fix screenshots in readme
change every var to const
bug fix (but also do some improvements)
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-11

NTUEEPLUS-11. fix readme screenshot, var to const

---

src/components/AppContent.js
src/scss/_layout.scss
src/views/components/column/Resume.js
src/views/components/column/css/default.css
src/views/components/column/css/layout.css

indent every subsection
reduce white and gray part and it won't change in different view percent!
delete subtitle's subtitle
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-15
150%:
100%:

NTUEEPLUS-15. Improve Appearance of Column Text

---

src/components/AppBreadcrumb.js
src/components/AppHeader.js
src/components/header/AppHeaderDropdown.js
yarn.lock

Header setting
Refactoring
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-14

NTUEEPLUS-14. Header setting

---

src/App.js
src/views/pages/forget/Forget.js

Forget Appearance
[ Feature ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-24

NTUEEPLUS-24. Forget Appearance

---

src/views/pages/login/Login.js

Login Functionality
[ Feature ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-20

NTUEEPLUS-20. Login Functionality

---

src/components/AppFooter.js
src/scss/_column.scss

create blue footer
Feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-36

NTUEEPLUS-36. footer

---

src/App.js
src/_navIn.js
src/views/pages/registerFB/RegisterFB.js

create registerFB page
feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-33
add registerfb in sidebar:
registerFB page:

NTUEEPLUS-33. finish registerfb appearance

---

src/views/pages/register/Register.js
src/views/pages/register/RegisterEntry.js

Register Function (state, function in frontend)
[ Feature ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-23
None

NTUEEPLUS-23. Register Functionality

---

src/views/pages/login/Login.js

FB login structure, but still need to connect with backend in the future.
[ Feature ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-21
None

NTUEEPLUS-21.  FB login

---

src/components/AppHeader.js
src/components/AppSidebar.js
src/scss/_custom.scss
src/views/components/history/HistBlock.js

add logo in sidebar when the screen is small
change sidebar's theme color into light
bug fix and improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-39
light theme sidebar:
when screen is small, logo still appears:
when screen is tiny, logo still appears:

NTUEEPLUS-39. adjust RWD and theme for sidebar

---

src/views/pages/profile/Profile.js

Create recuirtment in profile
Feature 
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-46

NTUEEPLUS-46. Create recuirtment in profile

---

src/components/AppContent.js
src/components/AppFooter.js
src/layout/DefaultLayout.js
src/scss/_column.scss
src/scss/_custom.scss
src/scss/_variables.scss
src/views/components/career/addRecommendation/addRecommendation.js
src/views/components/career/addRecruitment/addRecruitment.js
src/views/components/career/career.css
src/views/components/career/career.js
src/views/components/career/recommendation/Recommendation.js
src/views/components/career/recruitment/Recruitment.js
src/views/components/columnSummary/columnSummary.js
src/views/components/contact/Contact.js
src/views/components/history/Timeline.js

Fix the Footer's size and background colors.
[ Improvement |
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-40

NTUEEPLUS-40. Footer makes width of page bigger

---

src/views/pages/forget/Forget.js

Add state to forget.
[ Feature ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-25
None

NTUEEPLUS-25. Forget Functionality

---

client/src/_navIn.js
client/src/_navOut.js
client/src/scss/_custom.scss
client/src/views/components/career/recommendation/RecomPost.js
client/src/views/components/career/recommendation/Recommendation.css
client/src/views/components/career/recruitment/RecruPost.js
client/src/views/components/career/recruitment/Recruitment.css

use a big ass btn to let user add career
change the color of icons in sidebar
delete the title in sidebar
feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-49
no hover:
hovering:
sidebar:

NTUEEPLUS-49. create add btn and ch icon color in sidebar

---

client/package.json
client/src/App.js
client/src/_navOut.js
client/src/components/AppHeader.js
client/src/components/header/AppHeaderDropdown.js
client/src/store.js
client/src/views/dashboard/Dashboard.js
client/src/views/pages/login/Login.js

All the flow from login to logout.
[Feature]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-63
None

NTUEEPLUS-63. Login, LoginFB, LogOut

---

.env
backend/routes/middleware/validation/validFields.js
backend/routes/readme.md
backend/routes/srcs/out/account/main.js
backend/routes/srcs/out/account/registerFB.js

fix register export error
loginFB with validation check
Bug Fix 
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-73
throw error if without facebookID

NTUEEPLUS-73. Account security

---

client/src/components/AppContent.js
client/src/views/components/columnSummary/columnSummary.js

let every time url changes, the scrollbar automatic go to top
let every page change in columnSummary, the scrollbar automatic go to top
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-68

NTUEEPLUS-68. scrollbar to top

---

client/src/views/pages/forget/Forget.js
client/src/views/pages/register/RegisterEntry.js

Complete Forget Functionality.
[ Feature ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-67
None

NTUEEPLUS-67. Forget Complete.

---

client/src/components/AppSidebar.js

delete the onclick on the top of the sidebar
use useSelector to read isLogin and show corresponding sidebar
featur
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-76

NTUEEPLUS-76. Change sidebar depends on isLogin

---

backend/routes/Schemas/recommendation.js
backend/routes/Schemas/recruitment.js
backend/routes/Schemas/user_visual_new.js
backend/routes/readme.md
backend/routes/srcs/in/career/addRecruitment.js
backend/routes/srcs/in/career/main.js
backend/routes/srcs/in/career/smartSearch.js
backend/routes/srcs/in/profile_new/main.js
backend/routes/srcs/in/profile_new/smartSearch.js
backend/routes/srcs/in/recommendation/main.js
backend/routes/srcs/in/recommendation/smartSearch.js
backend/routes/srcs/out/forget/activation.js
backend/routes/srcs/out/forget/forget.js

use regex to search all field (frontend just need to post {keyword: ... }) on apis:
- /smartsearchProfile
- /smartsearchrecommendation
- /smartsearchRecruitment
forget using new profile schema
Bug Fix 
Improvement 
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-77
use {keyword:'google'} to match the field {'title.title':'找google內推'}

NTUEEPLUS-77. Search with reg and forget with profile_new

---

client/src/assets/icons/index.js
client/src/assets/icons/website.js
client/src/views/pages/profile/Profile.js

use axios to get profile from backend
Improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-82

NTUEEPLUS-82. Connect profile API (show)

---

backend/routes/Schemas/user_visual_new.js
backend/routes/readme.md
backend/routes/srcs/in/column/getDetail.js
backend/routes/srcs/in/column/getOutline.js
backend/routes/srcs/in/column/search.js
backend/routes/srcs/in/profile_new/searchProfile.js
backend/routes/srcs/in/profile_new/smartSearch.js
backend/routes/srcs/in/profile_new/updateProfile.js
backend/routes/srcs/in/recommendation/showRec.js

NTUEEPLUS-83. get with param, profile with github

---

client/src/components/header/AppHeaderDropdown.js
client/src/views/components/career/addRecommendation/addRecommendation.js
client/src/views/components/career/addRecruitment/addRecruitment.js
client/src/views/components/career/editRecruitment/editRecruitment.js
client/src/views/components/career/recommendation/RecomPost.js
client/src/views/components/career/recommendation/Recommendation.js
client/src/views/components/career/recruitment/Recruitment.js
package.json

use api to get every recruitment and recommendation
use api to add recruitment and recommendation
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-61

NTUEEPLUS-61. Add, show career api

---

client/src/components/AppBreadcrumb.js
client/src/routes.js
client/src/views/components/career/editRecruitment/editBlock.js
client/src/views/components/career/editRecruitment/editRecruitment.js
client/src/views/pages/profile/Profile.js
package.json

finish api for add and get for recruitment and recommendation in career page
finish api for get edit for recruitment in profile page
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-61

NTUEEPLUS-61. Career add, edit, get api

---

client/src/components/AppHeader.js
client/src/components/header/AppHeaderDropdown.js

Delete redundancy in right top corner
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-87

NTUEEPLUS-87. Delete redundancy in right top corner

---

client/src/components/index.js
client/src/views/components/career/editRecruitment/editBlock.js
client/src/views/components/career/editRecruitment/previewBlock.css
client/src/views/components/career/editRecruitment/previewBlock.js
client/src/views/components/career/recruitment/RecruBlock.js

create modal for previewing updated recruitment
change complete btn in edit recruitment block to show preview modal
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-89
bottom button:
after pressing Done button:
recruitment block:
preview block:

NTUEEPLUS-89. Create preview updated recruitment modal

---

client/src/views/pages/profile/Profile.js
client/src/views/pages/profileEdit/ProfileEdit.js

Add profile edit API
Feature 
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-93

NTUEEPLUS-93. Connect profile API (Edit)

---

client/src/App.js
client/src/_navIn.js
client/src/views/pages/recommendation/OwnRecommendation.js
client/src/views/pages/recommendation/RecomBlock.js
client/src/views/pages/recommendation/RecomPost.js
client/src/views/pages/recommendation/Recommendation.css
client/src/views/pages/recruitment/OwnRecruitment.js
client/src/views/pages/recruitment/RecruBlock.js
client/src/views/pages/recruitment/RecruPost.js
client/src/views/pages/recruitment/Recruitment.css

RT
Feature 
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-84

NTUEEPLUS-84. Create pages to show own post

---

.dockerignore
Dockerfile
README.md
backend/routes/Schemas/column_detail.js
backend/routes/Schemas/column_outline.js
backend/routes/Schemas/db.js
backend/routes/Schemas/preload.js
backend/routes/srcs/in/column/addColumn.js
backend/routes/srcs/in/column/getDetail.js
backend/routes/srcs/in/column/getOutline.js
backend/routes/srcs/in/column/preload/detail_preload.js
backend/routes/srcs/in/column/preload/outline_preload.js
backend/routes/srcs/in/column/search.js
docker-compose.yml
package.json

use docker to run mongoDB to fasten image load
Improvement 
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-107
https://drive.google.com/file/d/1pnlmedrCwIuWXh-QtL7QfbgEwxvpo9jk/view?usp=sharing

NTUEEPLUS-107. docker with mongodb image

---

client/src/store.js
client/src/views/components/column/Column.js
client/src/views/components/column/Resume.js
client/src/views/components/columnSummary/showColumns.js

use column/detail api to fetch specific column
use redux to store page
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-105

NTUEEPLUS-105. Use column detail api

---

backend/routes/srcs/in/column/preload/details/1808.js
client/src/views/components/career/addRecommendation/addRecommendation.js
client/src/views/components/career/addRecruitment/addRecruitment.js
client/src/views/components/career/editRecruitment/editBlock.js
client/src/views/components/career/recommendation/RecomPost.js
client/src/views/components/career/recommendation/Recommendation.css
client/src/views/components/career/recruitment/RecruBlock.js
client/src/views/components/career/recruitment/RecruPost.js
client/src/views/components/career/recruitment/Recruitment.css
client/src/views/pages/profile/Profile.js
client/src/views/pages/recommendation/RecomBlock.js
client/src/views/pages/recommendation/Recommendation.css
client/src/views/pages/recruitment/OwnRecruitment.js
client/src/views/pages/recruitment/RecruBlock.js
client/src/views/pages/recruitment/RecruPost.js
client/src/views/pages/recruitment/Recruitment.css

enable the trash can to delete corresponding recruitment
delete the add btn in all recruitment/recommendation 
delete recruitment in profile
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-91
profile:
recruitment:

NTUEEPLUS-91. Delete own recruitment api

---

client/src/views/components/career/addRecommendation/addRecommendation.js
client/src/views/components/career/addRecruitment/addRecruitment.js
client/src/views/components/career/editRecruitment/previewBlock.js

put preview block in add recruitment/recommendation
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-111
recommendation preview:

NTUEEPLUS-111. Add preview block in add career

---

client/package.json
client/src/App.js
client/src/components/AppHeader.js
client/src/components/AppSidebar.js
client/src/components/header/AppHeaderDropdown.js
client/src/slices/columnSummarySlice.js
client/src/slices/globalSlice.js
client/src/slices/index.js
client/src/slices/loginSlice.js
client/src/store/index.js
client/src/views/components/columnSummary/showColumns.js
client/src/views/pages/login/Login.js
client/src/views/pages/register/RegisterEntry.js

I add some file structure and introduce the redux toolkit to make redux much more easily to use.
[Improvement]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-109
None

NTUEEPLUS-109. Redux to Redux Slice

---

backend/routes/srcs/out/account/isLogin.js
backend/routes/srcs/out/account/login.js

return userimage  from isLogin
Improvement 
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-104

NTUEEPLUS-104. isLogin API return userimage

---

backend/routes/srcs/in/column/preload/detail_preload.js
backend/routes/srcs/out/account/isLogin.js

err handling
Bug Fix
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-113

NTUEEPLUS-113. isLogin with async handle

---

backend/routes/api.js
backend/routes/srcs/out/dashboard/main.js
backend/routes/srcs/out/dashboard/recentColumn.js
backend/routes/srcs/out/dashboard/recentRecommendation.js
backend/routes/srcs/out/dashboard/recentRecruitment.js

create dashboard API
Feature 
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-97

NTUEEPLUS-97. DashBoard

---

client/public/index.html
client/src/scss/_careerBlock.scss
client/src/slices/columnSummarySlice.js
client/src/views/components/column/Column.js
client/src/views/components/columnSummary/showColumns.js
client/src/views/pages/recommendation/RecomBlock.js
client/src/views/pages/recruitment/RecruBlock.js
package.json

finish all functionality for search certain keywords for column
Feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-114
main page
search key words:
by pressing "All Articles", it will go to main page:

NTUEEPLUS-114. Column search

---

client/src/views/components/career/recommendation/RecomBlock.js
client/src/views/components/career/recruitment/RecruBlock.js

RT
[ Feature ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-122
None

NTUEEPLUS-122. Add link in each career block.

---

client/src/routes.js
client/src/views/components/career/editRecommendation/editBlock.js
client/src/views/components/career/editRecommendation/editRecommendation.js
client/src/views/pages/recommendation/OwnRecommendation.js
client/src/views/pages/recommendation/RecomBlock.js
client/src/views/pages/recommendation/RecomPost.js

create page for editing recommendation
feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-129
edit page:
preview block:

NTUEEPLUS-129. Recommendation edit

---

client/src/views/components/contact/Contact.js

rewrite contact page which includes ig, fb, github links
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-126
contact page:

NTUEEPLUS-126. Contact page

---

client/src/views/in/career/Career.js
client/src/views/in/career/index.js
client/src/views/in/column/Column.js
client/src/views/in/column/Resume.js
client/src/views/in/column/Testimonials.js
client/src/views/in/column/Title.js
client/src/views/in/column/index.js
client/src/views/in/columnSummary/ColumnSummary.js
client/src/views/in/columnSummary/index.js
client/src/views/in/profile/Profile.js
client/src/views/in/profile/edit/ProfileEdit.js
client/src/views/in/profile/edit/ProfileImageEditor.js
client/src/views/in/profile/edit/index.js
client/src/views/in/profile/index.js
client/src/views/in/searchProfile/index.js

RT
[ Refactoring]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-132
None

NTUEEPLUS-132. In File Structure Refactor.

---

backend/routes/srcs/in/career/deleteRecruitment.js

NTUEEPLUS-134. Res => Req

---

backend/routes/srcs/in/career/deleteRecruitment.js

NTUEEPLUS-135. Or => And

---

backend/routes/srcs/in/career/addRecruitment.js
backend/routes/srcs/in/career/deleteRecruitment.js
backend/routes/srcs/in/career/updateRecruitment.js
backend/routes/srcs/in/recommendation/delRec.js
backend/routes/srcs/in/recommendation/updateRec.js

NTUEEPLUS-136. Faster Delete.

---

Dockerfile
README.md
client/webpack.config.js
docker-compose.yml
nginx/Dockerfile
nginx/nginx.conf

NTUEEPLUS-120. Deploy on GCP.

---

client/package.json
client/src/components/AppContent.js
client/src/slices/careerSlice.js
client/src/views/in/career/CareerImageEditor.js
client/src/views/in/career/CareerPreview.js
client/src/views/in/career/index.js
client/src/views/in/recommendation/RecommendationForm.js
client/src/views/in/recruitment/RecruitmentForm.js

RT
[ Feature ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-127

NTUEEPLUS-127. Career Image Editor Complete.

---

backend/routes/srcs/out/account/isLogin.js
client/src/components/AppContent.js
client/src/components/header/AppHeaderDropdown.js
client/src/slices/loginSlice.js
client/src/views/in/recommendation/RecommendationForm.js
client/src/views/in/recruitment/RecruitmentForm.js

Set required for title、name、desireWorkType in recommendation form and title in recruitment form
Use redux store user's phone, email, studentId, name, so that recommendation add form can auto complete some fields
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-139
use * to note required and auto complete
alert if you don't fill the required fields

NTUEEPLUS-139. Set required in career form and auto complete some fields in add recommendation form

---

.dockerignore
Dockerfile
README.md
cloudbuild.yaml
docker-compose.yml
gcloud.sh

use cloudbuild.yaml to auto deploy to gcp
Improvement

NTUEEPLUS-120. use cloudbuild.yaml to auto deploy to gcp

---

client/package.json
client/public/index.html
client/src/components/AppBackground.js
client/src/components/AppContent.js
client/src/components/index.js
client/src/scss/_custom.scss

Add Particle.js background animation
[ Feature ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-145

NTUEEPLUS-145. Background Animation Complete.

---

Dockerfile
package.json

NTUEEPLUS-149. engine version >=

---

client/src/App.js
client/src/components/AppContent.js
client/src/views/components/Spinner.js
client/src/views/in/columnSummary/ColumnSummary.js
client/src/views/in/columnSummary/index.js
client/src/views/in/recommendation/Recommendation.js
client/src/views/in/recommendation/index.js
client/src/views/in/recommendation/own/OwnRecommendation.js
client/src/views/in/recommendation/own/index.js
client/src/views/in/recruitment/Recruitment.js
client/src/views/in/recruitment/index.js
client/src/views/in/recruitment/own/OwnRecruitment.js
client/src/views/in/recruitment/own/index.js

Spinner is a component appears when data fetching
I put spinner in own career and center it
Improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-141

NTUEEPLUS-141. Put spinner in own career and center it

---

client/src/components/AppHeader.js
client/src/components/AppSidebar.js
client/src/slices/globalSlice.js

use menu icon in header to control showing the sidebar
Feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-146
hide sidebar:

NTUEEPLUS-146. Hide&Strech sidebar with menu icon

---

package.json

NTUEEPLUS-153. change webpack to yarn run webpack

---

client/src/views/out/home/history/Timeline.js

Add title in out history
Feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-155

NTUEEPLUS-155. Add history title

---

client/src/components/AppContent.js
client/src/routes.js
client/src/views/in/columnSummary/ColumnSummary.js
client/src/views/in/recommendation/Recommendation.js
client/src/views/in/recruitment/Recruitment.js

change "ALL" btn to home icon
change btns color to light
stretch search input length
Improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-157

NTUEEPLUS-157. Search prettier

---

client/src/components/AppContent.js
client/src/components/AppSidebar.js
client/src/scss/_custom.scss
client/src/scss/_outLanding.scss
client/src/views/dashboard/Dashboard.js

let sidebar be all white
let dashboard smaller and delete background
let title in dashboard look like home
Improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-158

NTUEEPLUS-158. Sidebar&Dashboard prettier

---

client/src/scss/_outLanding.scss
client/src/views/out/home/about/About.js
client/src/views/out/home/contact/Contact.js

RT, and some appearance changes
[ Improvement ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-160

NTUEEPLUS-160. Landing Page Contact.

---

backend/routes/readme.md
backend/routes/srcs/in/abroadInfo/getAbroadInfo.js
backend/routes/srcs/in/career/searchRecruitment.js
backend/routes/srcs/in/column/getDetail.js
backend/routes/srcs/in/column/getOutline.js
backend/routes/srcs/in/column/search.js
backend/routes/srcs/out/contact/main.js
backend/routes/srcs/out/dashboard/recentColumn.js
backend/routes/srcs/out/dashboard/recentRecommendation.js
backend/routes/srcs/out/dashboard/recentRecruitment.js

NTUEEPLUS-161. out contact with google form, readme prettier

---

client/src/scss/_careerBlock.scss
client/src/scss/_outLanding.scss
client/src/views/in/career/CareerBlock.js
client/src/views/in/career/CareerPreview.js
client/src/views/in/columnSummary/ColumnSummary.js
client/src/views/in/recommendation/Recommendation.js
client/src/views/in/recommendation/RecommendationForm.js
client/src/views/in/recommendation/own/OwnRecommendation.js
client/src/views/in/recruitment/Recruitment.js
client/src/views/in/recruitment/RecruitmentForm.js
client/src/views/in/recruitment/own/OwnRecruitment.js

delete border of picture in career block header
put space in career block img
put data instead of ~~~ in recruitment
masonry from two to three blocks per row
let required input border become red if it has no value
change add array btn position
Improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-156
career form:
after press preview:
recommendation:

NTUEEPLUS-156. Career form and block appearance

---

backend/routes/srcs/out/forget/forget.js
backend/routes/srcs/out/forget/mail/template_generator.js

NTUEEPLUS-174. link change to reset_password

---

backend/routes/Schemas/query.js
backend/routes/Schemas/recommendation.js
backend/routes/Schemas/recruitment.js
backend/routes/Schemas/user_visual_new.js
backend/routes/readme.md
backend/routes/srcs/in/career/searchRecruitment.js
backend/routes/srcs/in/career/showMyRecruitment.js
backend/routes/srcs/in/career/showRecruitment.js
backend/routes/srcs/in/career/smartSearch.js
backend/routes/srcs/in/column/getOutline.js
backend/routes/srcs/in/column/search.js
backend/routes/srcs/in/profile_new/searchProfile.js
backend/routes/srcs/in/profile_new/smartSearch.js
backend/routes/srcs/in/recommendation/showMyRec.js
backend/routes/srcs/in/recommendation/showRec.js
backend/routes/srcs/in/recommendation/smartSearch.js

NTUEEPLUS-166. mongoose count deprecated; find profile,career with page

---

backend/routes/Schemas/abroad_info.js
backend/routes/Schemas/column_outline.js
backend/routes/Schemas/query.js
backend/routes/Schemas/recommendation.js
backend/routes/Schemas/recruitment.js
backend/routes/Schemas/user_login.js
backend/routes/Schemas/user_pending.js
backend/routes/Schemas/user_visual.js
backend/routes/Schemas/user_visual_new.js

NTUEEPLUS-173. Buffer deprecated

---

client/src/assets/icons/index.js
client/src/views/out/home/contact/Contact.js

Contact function and icon.
[ Feature ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-165

NTUEEPLUS-164. Contact Function Complete.

---

backend/routes/readme.md
backend/routes/srcs/in/column/delete.js
backend/routes/srcs/in/column/main.js
backend/routes/srcs/in/column/update.js

api to edit and delete column 
Feature

NTUEEPLUS-92. api to edit and delete column 

---

client/src/scss/_careerBlock.scss
client/src/views/in/career/Career.js

Add title in career entry to let user know what is recruitment and recommendation
Adjust className and scss to perform RWD
Improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-168

NTUEEPLUS-168. Career Entry RWD

---

client/src/views/out/home/services/Services.js

RT
[ Feature ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-177

NTUEEPLUS-177. Add Service Content.

---

client/src/views/in/columnSummary/ColumnSummary.js
client/src/views/in/columnSummary/index.js

RT
[ Improvement ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-178

NTUEEPLUS-178. Column Author Snapshot Change.

---

backend/routes/Schemas/query.js
backend/routes/srcs/in/career/showMyRecruitment.js
backend/routes/srcs/in/recommendation/showMyRec.js
backend/routes/srcs/in/recommendation/showRec.js

NTUEEPLUS-179. fix body to query

---

backend/routes/readme.md
backend/routes/srcs/in/career/showRecruitment.js
backend/routes/srcs/in/recommendation/showRec.js
client/src/components/AppContent.js
client/src/scss/_custom.scss
client/src/views/in/recommendation/Recommendation.js
client/src/views/in/recruitment/Recruitment.js

Use pagination from material-ui to show more career posts
Let every material-ui pagination color become white
Improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-176

NTUEEPLUS-176. Pagination for career

---

client/src/views/in/profile/Profile.js
client/src/views/in/profile/edit/EditProfile.js

remove  input border and outline
save route connect
other small bugs
Improvement 
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-162

NTUEEPLUS-162. ProfileEdit  input adjust 

---

client/src/components/AppContent.js
client/src/views/dashboard/Dashboard.js
client/src/views/in/career/CareerBlock.js
client/src/views/in/columnSummary/ColumnSummary.js
client/src/views/in/profile/Profile.js
client/src/views/in/profile/edit/EditProfile.js
client/src/views/in/recommendation/Recommendation.js
client/src/views/in/recommendation/RecommendationForm.js
client/src/views/in/recommendation/own/OwnRecommendation.js
client/src/views/in/recruitment/Recruitment.js
client/src/views/in/recruitment/RecruitmentForm.js
client/src/views/in/recruitment/own/OwnRecruitment.js
client/src/views/out/home/contact/Contact.js
client/src/views/out/login/Login.js
client/src/views/out/registerEntry/RegisterEntry.js
client/src/views/out/registerFB/RegisterFB.js
client/src/views/out/resetPassword/ResetPassword.js

Delete frontend console.log
Improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-180

NTUEEPLUS-180. Delete console.log

---

backend/routes/middleware/fileProcess.js
backend/routes/readme.md
backend/routes/srcs/out/account/main.js
backend/routes/srcs/out/account/registerFB.js

NTUEEPLUS-96. registerFB with avatar

---

client/src/views/out/login/Login.js

RT
[Improvement]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-181
None

NTUEEPLUS-181. Login on Enter.

---

client/src/scss/_outLanding.scss
client/src/views/dashboard/Dashboard.js
client/src/views/in/career/CareerBlock.js
client/src/views/in/career/CareerPreview.js
client/src/views/in/columnSummary/ColumnSummary.js
client/src/views/in/recommendation/Recommendation.js
client/src/views/in/recommendation/edit/EditRecommendation.js
client/src/views/in/recruitment/Recruitment.js

Original code miss a layer of data
Also change interviews hover color
Bug Fix
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-186
Interviews hover color:

NTUEEPLUS-186. Fix edit recommendation

---

client/src/_navIn.js
client/src/routes.js
client/src/scss/_matching.scss
client/src/scss/style.scss
client/src/views/in/index.js
client/src/views/in/matching/Matching.js
client/src/views/in/matching/OpenMatching.js
client/src/views/in/matching/index.js

create a simple page for matching
feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-191
選擇身分頁面
秀出表單並填寫頁面
送出後進入開通後matching的主頁面

NTUEEPLUS-191. First simple open matching

---

client/src/scss/_matching.scss
client/src/views/in/matching/Experience.js
client/src/views/in/matching/MatchResult.js
client/src/views/in/matching/Matching.js
client/src/views/in/matching/OpenMatching.js

create matching page for common user to open matching functionality and show matching result
feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-193
first open when choosing identity:
ask to fill google form:
matching result:
matching result not ready:
sharing experience:

NTUEEPLUS-193. Matching page for common users

---

backend/routes/Schemas/time.js
backend/routes/api.js
backend/routes/srcs/in/time/getTime.js
backend/routes/srcs/in/time/main.js
backend/routes/srcs/in/time/setTime.js

create schema for time and create api for get&set
feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-209

NTUEEPLUS-209. Time api&schema

---

backend/routes/srcs/in/study/runMatch/getForm.js
client/src/components/AppContent.js
client/src/routes.js
client/src/views/in/index.js
client/src/views/in/matching/MatchResult.js
client/src/views/in/matching/Matching.js
client/src/views/in/matching/OpenMatching.js
client/src/views/in/matching/ResultBlock.js
client/src/views/in/matching/index.js
client/src/views/in/matching/matchForm/MatchForm.js
client/src/views/in/matching/matchForm/index.js

use new url to match form page
fetch old data in match form
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-208

NTUEEPLUS-208. Fetch old matching data

---

backend/routes/srcs/out/account/isLogin.js
backend/routes/srcs/out/account/login.js
client/src/components/AppContent.js
client/src/slices/loginSlice.js
client/src/views/out/login/Login.js
client/src/views/out/registerEntry/RegisterEntry.js

create an admin account and let website recognize it
feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-196

NTUEEPLUS-196. Recognize admin account

---

backend/routes/readme.md

write doc for get&set time apis
Documentation
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-213

NTUEEPLUS-213. Doc for time apis

---

backend/routes/srcs/in/study/storeMatch/mail.js
backend/routes/srcs/in/study/storeMatch/parseExcel.js
client/src/views/auth/matching/Mail.js
client/src/views/auth/matching/RunMatch.js

let sendmail api work
feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-218

NTUEEPLUS-218. Fix sendmail api

---

backend/routes/srcs/in/study/runMatch/matching.js
backend/routes/srcs/in/study/storeMatch/mail.js
backend/routes/srcs/in/study/storeMatch/mail/junior.html
backend/routes/srcs/in/study/storeMatch/mail/senior.html
backend/routes/srcs/in/study/storeMatch/parseExcel.js
client/src/scss/_matching.scss
client/src/views/auth/matching/Mail.js
client/src/views/auth/matching/RunMatch.js
client/src/views/auth/matching/index.js
client/src/views/in/matching/MatchResult.js

use send mail api to send mails to seniors&juniors
feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-217

NTUEEPLUS-217. Send Mails

---

backend/routes/srcs/in/study/runMatch/getForm.js
backend/routes/srcs/in/study/runMatch/matching.js
backend/routes/srcs/in/study/runMatch/parseExcel.js
backend/routes/srcs/in/study/storeMatch/sendmails.js
client/src/components/AppContent.js
client/src/scss/_matching.scss
client/src/views/auth/matching/RunMatch.js
client/src/views/in/matching/Matching.js
client/src/views/in/matching/OpenMatching.js
client/src/views/in/matching/matchForm/MatchForm.js

run whole process and make sure this work
Bug fix
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-216

NTUEEPLUS-216. Run all process

---

client/package.json
client/src/components/AppBackground.js

tsparticles
bug fix
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-219

NTUEEPLUS-219. Tsparticles

---

client/package.json

NTUEEPLUS-220. react-tsparticles

---

client/webpack.config.js

NTUEEPLUS-222. webpack process for GCP

---

backend/routes/srcs/in/study/runMatch/matching.js
backend/routes/srcs/in/study/storeMatch/mail/junior.html
client/package.json
client/src/views/auth/matching/Matching.js
client/src/views/auth/matching/RunMatch.js
client/src/views/in/matching/Experience.js
client/src/views/in/matching/Matching.js
package.json

adjust whole file to be same as hw repo except the cicon attr
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-223

NTUEEPLUS-223. Same as hw repo

---

backend/routes/srcs/out/account/register.js
client/src/_navAuth.js
client/src/assets/icons/index.js
client/src/routes.js
client/src/scss/_register.scss
client/src/scss/style.scss
client/src/views/auth/index.js
client/src/views/auth/register/Applicant.js
client/src/views/auth/register/Register.js
client/src/views/auth/register/index.js

When a person register, its account will be send to pending. I create a page for admin to verify those pending accounts to activate them
feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-230

NTUEEPLUS-230. Create a page for admin to verify pending account

---

client/src/views/out/home/team/Team.js

Team members photos.
Bug Fix
no
https://ntueeplus.atlassian.net/jira/software/c/projects/NTUEEPLUS/boards/2?selectedIssue=NTUEEPLUS-234

NTUEEPLUS-234. Team members photos.

---

client/src/scss/_careerBlock.scss

conceal fullsize button
Bug Fix
https://ntueeplus.atlassian.net/jira/software/c/projects/NTUEEPLUS/boards/2?modal=detail&selectedIssue=NTUEEPLUS-239

NTUEEPLUS-239. conceal fullsize button

---

backend/routes/srcs/in/career/smartSearch.js
backend/routes/srcs/in/recommendation/smartSearch.js
client/src/views/in/recommendation/Recommendation.js
client/src/views/in/recruitment/Recruitment.js

search problems
Bug Fix 
https://ntueeplus.atlassian.net/jira/software/c/projects/NTUEEPLUS/boards/2?modal=detail&selectedIssue=NTUEEPLUS-238

NTUEEPLUS-238. Search in career (both recruitment and recommendation) cannot work

---

client/src/views/auth/register/Register.js

auto fetch pending data after admin verify/reject register request
bug fix
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-237

NTUEEPLUS-237. Auto fetch pending data

---

client/src/views/auth/register/Register.js
client/src/views/out/register/Register.js

add isGraduated in register form
don't use setstate to update email, directly append in form data
bug fix
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-235

NTUEEPLUS-235. Fix register bug

---

backend/routes/srcs/in/account/chPassword.js
client/src/components/header/AppHeaderDropdown.js
client/src/routes.js
client/src/views/in/changePsw/ChangePsw.js
client/src/views/in/changePsw/index.js
client/src/views/in/index.js

Add change password page
Feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-241

NTUEEPLUS-241. change password page

---

client/src/views/in/profile/Profile.js
client/src/views/in/profile/edit/EditProfile.js

Solve the race condition when edit profile.
Improvement 
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-240

NTUEEPLUS-240. won't update profile in real-time after alert completed

---

backend/routes/middleware/mail/main.js
backend/routes/srcs/in/study/storeMatch/mail.js
backend/routes/srcs/in/study/storeMatch/mail/senior.html
backend/routes/srcs/in/study/storeMatch/sendmails.js
client/src/views/auth/matching/RunMatch.js

allow to modify the period
send backup to admin
[ Improvement ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-229
None

NTUEEPLUS-229. Modify the workflow of matching.

---

client/package.json
client/src/components/AppBackground.js
package.json

update tsparticles code because it updates
Hot Fix
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-242

NTUEEPLUS-242. Update tsparticles

---

backend/routes/srcs/out/account/register.js
docker-compose.yml

RT
[Bug Fix]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-245

NTUEEPLUS-245. isGraduated is string not boolean

---

client/src/views/out/register/Register.js
docker-compose.yml

RT
[Bug Fix ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-246

NTUEEPLUS-246. fix docker-compose and Register logic

---

client/src/views/in/columnSummary/ColumnSummary.js
client/src/views/in/recommendation/Recommendation.js
client/src/views/in/recruitment/Recruitment.js

change text color to white when no searching result
show all posts when searching keyword is empty
improvement
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-244

NTUEEPLUS-243. Change text to white and get all data when input is empty

---

Dockerfile
README.md
backend/index.js
docker-compose.yml

change port in docker to 1993
bug fix
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-247

NTUEEPLUS-247. Change port in docker to 1993

---

backend/routes/Schemas/preload.js

deconstruct obj in preoad
bug fix
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-249

NTUEEPLUS-249. Two obj in preload

---

backend/routes/srcs/in/account/auth/handlePending.js
backend/routes/srcs/out/account/activate.js
backend/routes/srcs/out/account/mailTemplate/accountActivate.html
backend/routes/srcs/out/account/register.js
backend/routes/srcs/out/account/registerFB.js
backend/routes/srcs/out/forget/forget.js
backend/routes/srcs/out/forget/mail/resetPassword.html

delete # in register mail
bug fix
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-250

NTUEEPLUS-250. Delete fixed mail url

---

.env.defaults
backend/routes/srcs/out/account/activate.js

add WEB_DOMAIN
[ Improvement ]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-251

NTUEEPLUS-251. Modify .env.default

---

README.md

RT
[Documentation]
None
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-252
None

NTUEEPLUS-252. Modify Readme

---

backend/routes/Schemas/announcement.js
backend/routes/api.js
backend/routes/srcs/in/announcement/addAnnouncement.js
backend/routes/srcs/in/announcement/deleteAnnouncement.js
backend/routes/srcs/in/announcement/editAnnouncement.js
backend/routes/srcs/in/announcement/getAnnouncement.js
backend/routes/srcs/in/announcement/main.js
backend/routes/srcs/in/announcement/searchAnnouncement.js
backend/routes/srcs/in/announcement/smartSearch.js
backend/routes/srcs/in/dashboard/main.js
backend/routes/srcs/in/dashboard/recentAnnouncement.js
backend/routes/srcs/in/dashboard/recentRecommendation.js
backend/routes/srcs/in/dashboard/recentRecruitment.js
client/src/components/AppContent.js
client/src/routes.js
client/src/scss/_auth-register.scss
client/src/scss/_careerBlock.scss
client/src/scss/_recent.scss
client/src/scss/style.scss
client/src/views/auth/announce/Announce.js
client/src/views/auth/announce/index.js
client/src/views/auth/index.js
client/src/views/dashboard/Dashboard.js
client/src/views/dashboard/index.js
client/src/views/in/recruitment/RecruitmentForm.js

let admin can create announcements to let every user see
feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-254

NTUEEPLUS-254. Announcement in dashboard

---

backend/routes/readme.md
backend/routes/srcs/in/account/auth/deleteUser.js
backend/routes/srcs/in/account/auth/handlePending.js
backend/routes/srcs/in/account/auth/history/addHist.js
backend/routes/srcs/in/account/auth/history/delHist.js
backend/routes/srcs/in/account/auth/history/updateHist.js
backend/routes/srcs/in/account/auth/manageAuth.js
backend/routes/srcs/in/account/auth/showPending.js
backend/routes/srcs/in/account/auth/teamData/addTeam.js
backend/routes/srcs/in/account/auth/teamData/delTeam.js
backend/routes/srcs/in/account/auth/teamData/updateTeam.js
backend/routes/srcs/in/account/chPassword.js
backend/routes/srcs/in/account/showPersonal.js
backend/routes/srcs/in/dashboard/recentAnnouncement.js
backend/routes/srcs/in/dashboard/recentColumn.js
backend/routes/srcs/in/dashboard/recentRecommendation.js
backend/routes/srcs/in/dashboard/recentRecruitment.js
backend/routes/srcs/in/study/addLink.js
backend/routes/srcs/in/study/getLinks.js
backend/routes/srcs/in/study/runMatch/index.js
backend/routes/srcs/in/study/storeMatch/index.js
backend/routes/srcs/out/publicData/getHist.js
backend/routes/srcs/out/publicData/getHistImg.js
backend/routes/srcs/out/publicData/getTeam.js

changing English route name to Chinese
correcting the apiGroup of some routes (view Jira for more info)
correcting default value format to what apiDoc intended
Documentation
Retrospecting the whole document for adding more example and following the correct style of apiDoc
[NTUEEPLUS-259 finish backend doc](https://ntueeplus.atlassian.net/browse/NTUEEPLUS-259?atlOrigin=eyJpIjoiYmUxYzJiYzllMzNlNDhkZTlhN2E2ODFjM2NhNzUyMTYiLCJwIjoiaiJ9)

NTUEEPLUS-259. Correct Error In Docs

---

client/src/views/out/login/Login.js
client/src/views/out/register/Register.js
client/src/views/out/resetPassword/ResetPassword.js

Add an icon button for users to view their typed password or hide it.
Improvement
None
[NTUEEPLUS-268](https://ntueeplus.atlassian.net/browse/NTUEEPLUS-268). show password
1. Register
2. Login
3. Reset password
[NTUEEPLUS-268]: https://ntueeplus.atlassian.net/browse/NTUEEPLUS-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NTUEEPLUS-268. show password

---

client/src/scss/_column.scss
client/src/views/in/column/Column.js
client/src/views/in/column/Testimonials.js
client/src/views/in/column/Title.js

Improve the visual of "Column."
Improvement
[NTUEEPLUS-106](https://ntueeplus.atlassian.net/browse/NTUEEPLUS-106)
1. Change the background, the layout and the font size format
2. Resize the background image to match the webpage width and reformat the content.
[NTUEEPLUS-106]: https://ntueeplus.atlassian.net/browse/NTUEEPLUS-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NTUEEPLUS-106. css in bottom of column

---

backend/routes/srcs/in/recommendation/showMyRec.js
client/src/scss/_careerBlock.scss
client/src/scss/_matching.scss
client/src/views/in/changePsw/ChangePsw.js
client/src/views/in/column/Column.js
client/src/views/in/column/Testimonials.js
client/src/views/in/column/index.js
client/src/views/in/columnSummary/ColumnSummary.js
client/src/views/in/matching/matchForm/MatchForm.js
client/src/views/in/profile/Profile.js
client/src/views/in/profile/edit/EditProfile.js
client/src/views/in/recommendation/Recommendation.js
client/src/views/in/recommendation/RecommendationForm.js
client/src/views/in/recommendation/own/OwnRecommendation.js
client/src/views/in/recruitment/RecruitmentForm.js
client/src/views/in/recruitment/own/OwnRecruitment.js
client/src/views/out/forget/Forget.js
client/src/views/out/login/Login.js
client/src/views/out/register/Register.js
client/src/views/out/resetPassword/ResetPassword.js

use more rwd and delete hover to let mobile users easier
improvement
https://ntueeplus.atlassian.net/jira/software/c/projects/NTUEEPLUS/issues/NTUEEPLUS-271

NTUEEPLUS-271. Mobile friendly

---

client/src/views/out/register/Register.js

alert user when they don't upload their certificate
improvement
https://ntueeplus.atlassian.net/jira/software/c/projects/NTUEEPLUS/issues/NTUEEPLUS-273

NTUEEPLUS-273. Alert when not upload at registry

---

backend/routes/srcs/in/study/runMatch/getForm.js
client/src/views/auth/matching/RunMatch.js
client/src/views/in/matching/matchForm/MatchForm.js

date in match form is static, I fix it
Bug Fix
https://ntueeplus.atlassian.net/jira/software/c/projects/NTUEEPLUS/issues/NTUEEPLUS-274

NTUEEPLUS-274. Fix date in match form

---

client/src/views/in/recommendation/RecommendationForm.js
client/src/views/out/register/Register.js

modify activation term
fix update recommendation bug
bug fix
https://ntueeplus.atlassian.net/jira/software/c/projects/NTUEEPLUS/issues/NTUEEPLUS-275

NTUEEPLUS-275. Activate term and Update recommendation

---

client/src/views/out/register/Register.js

show password in register has bug
bug fix
https://ntueeplus.atlassian.net/jira/software/c/projects/NTUEEPLUS/issues/NTUEEPLUS-277

NTUEEPLUS-277. Fix show password

---

backend/routes/middleware/validation/Name/Url.js
backend/routes/srcs/in/abroadSharing/addAbroadSharing.js
backend/routes/srcs/in/abroadSharing/getoneAbroadSharing.js
backend/routes/srcs/in/abroadSharing/updateAbroadSharing.js
client/src/views/in/abroadSession/AbroadSession.js
client/src/views/in/abroadSession/components/FormModal.js

A few modification so that sharing session data can be without YTlink
Feature
None
[NTUEEPLUS-281](https://ntueeplus.atlassian.net/jira/software/c/projects/NTUEEPLUS/issues/NTUEEPLUS-281)
[NTUEEPLUS-281]: https://ntueeplus.atlassian.net/browse/NTUEEPLUS-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NTUEEPLUS-281. YTlink in abroad sharing session not required

---

backend/routes/Schemas/query.js
backend/routes/srcs/in/column/getOutline.js
backend/routes/srcs/in/column/search.js
client/src/views/in/column/Column.js
client/src/views/in/columnSummary/ColumnSummary.js
client/src/views/in/columnSummary/ImageLoader.js

Let image loading won't block page rendering
Improvement
None
[NTUEEPLUS-282](https://ntueeplus.atlassian.net/browse/NTUEEPLUS-282)
[NTUEEPLUS-282]: https://ntueeplus.atlassian.net/browse/NTUEEPLUS-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NTUEEPLUS-282. lazy load column image

---

client/src/components/AppContent.js
client/src/components/header/AppHeaderDropdown.js
client/src/views/auth/column/ColumnPreview.js
client/src/views/out/login/Login.js

Redirecting to the log-in page if users have not logged in yet at "in-route", and redirecting them back to the original page after logging in.
Feature
* (Maybe) add a page (or redirection to home) at the root route
[NTUEEPLUS-284](https://ntueeplus.atlassian.net/browse/NTUEEPLUS-284)
[NTUEEPLUS-284]: https://ntueeplus.atlassian.net/browse/NTUEEPLUS-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NTUEEPLUS-284. routes after login

---

client/src/layout/DefaultLayout.js
client/src/views/in/recruitment/Recruitment.js
client/src/views/out/register/Register.js

use modal to enforce users to change their password and recommend them don't use the same password
Improvement
https://ntueeplus.atlassian.net/jira/software/c/projects/NTUEEPLUS/issues/NTUEEPLUS-285

NTUEEPLUS-285. Reset password modal

---

backend/package.json
backend/routes/Schemas/preload.js
backend/routes/Schemas/update_psw.js
backend/routes/encrypt/index.js
backend/routes/srcs/in/account/chPassword.js
backend/routes/srcs/out/account/login.js
backend/routes/srcs/out/account/loginFB.js
backend/routes/srcs/out/account/register.js
backend/routes/srcs/out/account/registerFB.js
backend/routes/srcs/out/forget/activation.js
client/src/layout/DefaultLayout.js
client/src/views/auth/column/Page3.js
client/src/views/in/columnSummary/ColumnSummary.js
client/src/views/in/profile/Profile.js
client/src/views/in/profile/edit/EditProfile.js
client/src/views/in/recruitment/Recruitment.js
client/src/views/out/register/Register.js

let bcrypt directly after md5 s.t. so we can have better security
Improvement
```javascript
// userPsw is the hashed passwords stored in the db
function mapFunc({userpsw}){
const saltRounds = 10
const salt = await bcrypt.genSalt(saltRounds)
return await bcrypt.hash(userPsw, salt)
}
```
[NTUEEPLUS-287](https://ntueeplus.atlassian.net/browse/NTUEEPLUS-287)
[NTUEEPLUS-287]: https://ntueeplus.atlassian.net/browse/NTUEEPLUS-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NTUPLUSS-287. use better encrypt method

---

backend/routes/Schemas/recruitment.js
backend/routes/srcs/in/recruitment/addRecruitment.js
backend/routes/srcs/in/recruitment/updateRecruitment.js
client/src/views/in/career/CareerBlock.js
client/src/views/in/dashboard/Dashboard.js
client/src/views/in/recruitment/Recruitment.js
client/src/views/in/recruitment/RecruitmentForm.js
package.json

Enable the hide function in the recruitment block.  When 'hide' is enabled, the block will disappear in the dashboard and RecruitmentBlock, will only show in one's editRecruitment page.
Feature
https://ntueeplus.atlassian.net/browse/NTUEEPLUS-290

NTUEEPLUS-290

---

backend/routes/error/index.js
client/src/views/out/login/Login.js
doc/contribution.md

redirect the page to "/dashboard"after login
Improvement
redirect the page to "/dashboard"after login
jira is dead

redirect to dashboard after login and fix some typo

---

client/package.json
client/src/components/ResImage.js
client/src/components/index.js
client/src/views/out/home/services/Services.js
client/webpack.config.js

Use .webp format as the default image type. Add the responsive image for further improvement. (See Service.js for example usage)
Improvement
Forget

NTUEEPLUS-299 ? Use webp for frontend (static) images & Add responsive image

---

client/src/views/in/material/Medium.js

NTUEEPLUS-297. add medium

---

client/src/views/auth/matching/RunMatch.js
client/src/views/in/index.js

enable 留學配對
暫時把 需要送信的條件關掉，上一期應該手動寄信過了

Ntueeplus 305

---

client/src/views/auth/matching/RunMatch.js

Ntueeplus 321
